//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResumoFat
    {
        public string codigo_fat { get; set; }
        public string dt_criacao { get; set; }
        public string dt_emissao { get; set; }
        public string estado { get; set; }
        public Nullable<decimal> val_total { get; set; }
        public Nullable<int> val_iva { get; set; }
        public string nome { get; set; }
        public decimal nif { get; set; }
    }
}
