//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP2.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fatura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fatura()
        {
            this.Fatura_Hist = new HashSet<Fatura_Hist>();
            this.Item = new HashSet<Item>();
            this.Item_Hist = new HashSet<Item_Hist>();
            this.Nota_Cred = new HashSet<Nota_Cred>();
        }
    
        public string codigo_fat { get; set; }
        public decimal ano { get; set; }
        public decimal nr_fat { get; set; }
        public string dt_emissao { get; set; }
        public string dt_criacao { get; set; }
        public Nullable<decimal> val_total { get; set; }
        public Nullable<int> val_iva { get; set; }
        public string estado { get; set; }
        public Nullable<decimal> nif { get; set; }
    
        public virtual Codigo_Fatura Codigo_Fatura { get; set; }
        public virtual Contribuinte Contribuinte { get; set; }
        public virtual Estado_FAT Estado_FAT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fatura_Hist> Fatura_Hist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item> Item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_Hist> Item_Hist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nota_Cred> Nota_Cred { get; set; }
    }
}
