//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP2.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_NC
    {
        public int quantidade { get; set; }
        public string codigo_nc { get; set; }
        public Nullable<int> num_item { get; set; }
        public string codigo_fat { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Nota_Cred Nota_Cred { get; set; }
    }
}
