//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP2.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nota_Cred
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Nota_Cred()
        {
            this.Item_NC = new HashSet<Item_NC>();
        }
    
        public string codigo_nc { get; set; }
        public decimal ano { get; set; }
        public decimal nr_nc { get; set; }
        public string dt_emissao { get; set; }
        public string dt_criacao { get; set; }
        public Nullable<decimal> val_nc { get; set; }
        public string estado { get; set; }
        public string codigo_fat { get; set; }
    
        public virtual Codigo_NotaCred Codigo_NotaCred { get; set; }
        public virtual Estado_NC Estado_NC { get; set; }
        public virtual Fatura Fatura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_NC> Item_NC { get; set; }
    }
}
