USE SI2Trab1;

GO

CREATE OR ALTER PROCEDURE drop_tables
AS
	DROP TABLE IF EXISTS Item_Hist;
	DROP TABLE IF EXISTS Fatura_Hist;
	DROP TABLE IF EXISTS Item_NC;
	DROP TABLE IF EXISTS Item;
	DROP TABLE IF EXISTS Produto;
	DROP TABLE IF EXISTS Nota_Cred;
	DROP TABLE IF EXISTS Fatura;
	DROP TABLE IF EXISTS Contribuinte;
	DROP TABLE IF EXISTS Codigo_Fatura;
	DROP TABLE IF EXISTS Codigo_NotaCred;
	DROP TABLE IF EXISTS Estado_NC;
	DROP TABLE IF EXISTS Estado_FAT;

GO

EXEC drop_tables;